app:
  region: us-west-2
  environment: dev
  vpc_cluster: inseng-dev
  security_groups:
    pods:
      allow_internal_traffic: true
      rules:
      - source: sg-01519684aeab3782f
        ports: 8443
        protocol: tcp
  databases:
    api:
      allocated_storage: 20
      db_instance_class: db.t2.small
      engine_version: '10'
      env_var_prefix: DB
      master_username: todoapp_postgres_user
      storage_type: gp2
  instance_pools:
    web:
      hooks:
        pre: bundle exec rake db:migrate
      instance_type: t4g.small
      instance_type_overrides:
        - instance_type: "t4g.small"
          weighted_capacity: "1"
        - instance_type: "t3.small"
          weighted_capacity: "1"
      instances_distribution:
        on_demand_base_capacity: 0
        on_demand_percentage_above_base_capacity: 0
      max_size: 2
      min_size: 1
  load_balancers:
    web:
      ssl_cert_arn: arn:aws:acm:us-west-2:830473435438:certificate/b119c8b6-9305-4532-9798-dcfbf712158b
  terraform:
    dev: {}

